name: Make Bootstrap

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Bootstrap
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v3.2.0
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        uses: actions/checkout@v3.2.0
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Caching
        id: SDK
        uses: actions/cache@v3.2.0
        env:
          cache-name: iOS-15.5-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}

      - name: Download iOS 15.5 SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          svn checkout -q https://github.com/chrisharper22/sdks/trunk/iPhoneOS15.5.sdk
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main       
          make package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Bootstrap
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
